/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FontDialog.java
 *
 * Created on 01-Mar-2010, 00:16:42
 */

package jettyplay;

import java.awt.GraphicsEnvironment;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author ais523
 */
public class FontDialog extends javax.swing.JDialog {

    private final MainFrame sendFontActionsTo;

    /** Creates new form FontDialog
     * @param parent The frame that this dialog box belongs to
     * @param sendFontActionsTo The JettyView to send font actions to
     */
    public FontDialog(java.awt.Frame parent, MainFrame sendFontActionsTo) {
        super(parent, true);
        this.sendFontActionsTo = sendFontActionsTo;
        this.setTitle("Set Font");
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        fontComboBoxLabel = new javax.swing.JLabel();
        fontComboBox = new javax.swing.JComboBox();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        fontComboBoxLabel.setLabelFor(fontComboBox);
        fontComboBoxLabel.setText("Display using which font?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = null;
        getContentPane().add(fontComboBoxLabel, gridBagConstraints);

        fontComboBox.setModel(new DefaultComboBoxModel(
            GraphicsEnvironment.getLocalGraphicsEnvironment().
            getAvailableFontFamilyNames()));
    fontComboBox.getModel().setSelectedItem(
        sendFontActionsTo.getTerminalFont().getFamily());
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = null;
    getContentPane().add(fontComboBox, gridBagConstraints);

    cancelButton.setMnemonic('c');
    cancelButton.setText("Cancel");
    cancelButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cancelButtonActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = null;
    getContentPane().add(cancelButton, gridBagConstraints);

    okButton.setMnemonic('s');
    okButton.setText("Set Font");
    okButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            okButtonActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
    gridBagConstraints.insets = null;
    getContentPane().add(okButton, gridBagConstraints);

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        sendFontActionsTo.setTerminalFont(
                (String) fontComboBox.getModel().getSelectedItem());
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox fontComboBox;
    private javax.swing.JLabel fontComboBoxLabel;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

    void fixDefaultFocus() {
        getRootPane().setDefaultButton(okButton);
    }

}
